from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Dict, Iterable, List
from urllib.request import Request, urlopen

RELEASES_API_URL = "https://api.github.com/repos/bogdanfinn/tls-client/releases"
PROFILES_URL = "https://raw.githubusercontent.com/bogdanfinn/tls-client/refs/heads/master/profiles/profiles.go"

DEPENDENCY_TARGETS = {
    "windows-32": "tls-client-32.dll",
    "windows-64": "tls-client-64.dll",
    "darwin-arm64": "tls-client-arm64.dylib",
    "darwin-amd64": "tls-client-x86.dylib",
    "linux-alpine-amd64": "tls-client-amd64.so",
    "linux-ubuntu-amd64": "tls-client-x86.so",
    "linux-arm64": "tls-client-arm64.so",
}


def http_get(url: str, timeout: int) -> bytes:
    request = Request(url, headers={"User-Agent": "better-tls-client-updater"})
    with urlopen(request, timeout=timeout) as response:
        return response.read()


def fetch_release(version: str | None) -> Dict:
    if version:
        url = f"{RELEASES_API_URL}/tags/v{version}"
    else:
        url = f"{RELEASES_API_URL}/latest"

    return json.loads(http_get(url, timeout=30).decode("utf-8"))


def pick_asset_url(assets: Iterable[Dict], asset_key: str) -> str:
    for asset in assets:
        if asset_key in asset["name"]:
            return asset["browser_download_url"]
    raise ValueError(f"unable to find release asset containing '{asset_key}'")


def update_dependencies(assets: List[Dict], repo_root: Path) -> None:
    dependencies_dir = repo_root / "tls_client" / "dependencies"
    dependencies_dir.mkdir(parents=True, exist_ok=True)

    for asset_key, dependency_filename in DEPENDENCY_TARGETS.items():
        url = pick_asset_url(assets, asset_key)
        output_file = dependencies_dir / dependency_filename
        output_file.write_bytes(http_get(url, timeout=60))
        print(f"updated dependency: {output_file.name}")


def fetch_client_identifiers() -> List[str]:
    profile_file = http_get(PROFILES_URL, timeout=30).decode("utf-8")
    map_body_match = re.search(
        r"var MappedTLSClients = map\[string\]ClientProfile\{(?P<body>.*?)\n\}",
        profile_file,
        re.DOTALL,
    )
    if map_body_match is None:
        raise ValueError("unable to locate MappedTLSClients in profiles.go")

    map_body = map_body_match.group("body")
    identifiers = re.findall(r'"([^"]+)"\s*:', map_body)
    if not identifiers:
        raise ValueError("no client identifiers found in MappedTLSClients")

    # Preserve map order while removing duplicates.
    return list(dict.fromkeys(identifiers))


def write_settings_py(client_identifiers: List[str], repo_root: Path) -> None:
    settings_path = repo_root / "tls_client" / "settings.py"

    literal_lines = [f'    "{identifier}",' for identifier in client_identifiers]
    output = [
        "from typing_extensions import Literal, TypeAlias",
        "",
        "# Auto-generated by scripts/update_shared_libraries.py.",
        "ClientIdentifiers: TypeAlias = Literal[",
        *literal_lines,
        "]",
        "",
    ]
    settings_path.write_text("\n".join(output), encoding="utf-8")
    print(f"updated client identifiers: {settings_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Update shared libraries and sync client identifiers from bogdanfinn/tls-client."
    )
    parser.add_argument(
        "--version",
        help="tls-client release version without leading 'v' (defaults to latest release)",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    release = fetch_release(args.version)
    release_tag = release["tag_name"]
    print(f"using tls-client release: {release_tag}")

    update_dependencies(release["assets"], repo_root)
    client_identifiers = fetch_client_identifiers()
    write_settings_py(client_identifiers, repo_root)


if __name__ == "__main__":
    main()
